---
- name: Copy file to /etc/apt/preferences to enable Trusty Backports
  copy: src=files/preferences dest=/etc/apt/preferences

- name: First list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - apache2
    - libapache2-mod-php5

- name: Second list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - php5-gd
    - php5-json
    - php5-mysql
    - php5-curl

- name: Third list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - php5-intl
    - php5-mcrypt
    - php5-imagick

- name: Run manual install of php5-apcu/trusty-backports
  shell: apt-get install -y php5-apcu/trusty-backports

- name: Install postfix
  apt:
    name: postfix
    state: present

- name: Equivilent of apt-get upgrade
  apt: upgrade=dist
